### ISSUE TITLE
Attempt to build by erlang.mk

### ISSUE THREAD

**Issue by zamotivator** [talentdeficit/jsxn#3]
What I am doing wrong?
➜ make all
Cloning into '/home/oleg/dev/qlp/deps/jsx'...
remote: Counting objects: 4900, done.
remote: Total 4900 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (4900/4900), 2.24 MiB | 608.00 KiB/s, done.
Resolving deltas: 100% (2717/2717), done.
Checking connectivity... done.
Cloning into '/home/oleg/dev/qlp/deps/jsxn'...
remote: Counting objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (45/45), done.
Checking connectivity... done.
make[1]: вход в каталог «/home/oleg/dev/qlp/deps/lager»
test -d deps || ./rebar get-deps
==> goldrush (get-deps)
==> lager (get-deps)
./rebar compile
==> goldrush (compile)
==> lager (compile)
make[1]: выход из каталога «/home/oleg/dev/qlp/deps/lager»
make[1]: вход в каталог «/home/oleg/dev/qlp/deps/cowboy»
make[2]: вход в каталог «/home/oleg/dev/qlp/deps/cowlib»
 APP    cowlib.app.src
make[2]: выход из каталога «/home/oleg/dev/qlp/deps/cowlib»
make[2]: вход в каталог «/home/oleg/dev/qlp/deps/ranch»
 APP    ranch.app.src
make[2]: выход из каталога «/home/oleg/dev/qlp/deps/ranch»
 APP    cowboy.app.src
make[1]: выход из каталога «/home/oleg/dev/qlp/deps/cowboy»
make[1]: вход в каталог «/home/oleg/dev/qlp/deps/sync»
./rebar compile
==> sync (compile)
make[1]: выход из каталога «/home/oleg/dev/qlp/deps/sync»
make[1]: вход в каталог «/home/oleg/dev/qlp/deps/mimetypes»
 APP    mimetypes.app.src
make[1]: выход из каталога «/home/oleg/dev/qlp/deps/mimetypes»
make[1]: вход в каталог «/home/oleg/dev/qlp/deps/jsx»
 ERLC   jsx_to_term.erl jsx_verify.erl jsx_parser.erl jsx_to_json.erl jsx_config.erl jsx_encoder.erl jsx_decoder.erl jsx.erl
Old inliner: threshold=0 functions=[{doublequote,5},
                                    {singlequote,5},
                                    {maybe_replace,2},
                                    {format_number,1},
                                    {handle_event,3},
                                    {new_seq,0},
                                    {new_seq,1},
                                    {acc_seq,2},
                                    {end_seq,1},
                                    {end_seq,2}]
 APP    jsx.app.src
make[1]: выход из каталога «/home/oleg/dev/qlp/deps/jsx»
make[1]: вход в каталог «/home/oleg/dev/qlp/deps/jsxn»
 ERLC   jsxn.erl
 APP    jsxn.app.src
make[1]: выход из каталога «/home/oleg/dev/qlp/deps/jsxn»
 APP    qlp.app.src

➜ erl -pa ./deps/*/ebin
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.2  (abort with ^G)
1> 
1> jsxn:encode(#{ok => 1}).
** exception error: bad argument
     in function  jsx_parser:value/4 (src/jsx_parser.erl, line 135)
2>

**Comment by essen** [comment]
This is no longer accurate, both jsx and jsxn compile fine now. I will add jsxn to the index today also.

This can be closed.
